type: object
properties:
  name:
    type: string
    format: media_name
    description: Globally unique balancer name.
    x-primary-key: true

  servers:
    type: array
    items:
      allOf:
      - $ref: '../../schemas.yml#/balancer_server_config'
    nullable: true
    description: Balancer will distribute requests between these servers.

  peers:
    description: Configuration of the peers.
    type: array
    items:
      allOf:
      - $ref: '../../schemas.yml#/peer_config'
    nullable: true
    deprecated: true
    x-delete-at: 23.09

  mode:
    description: Balancing mode
    type: string
    default: bitrate
    oneOf:
    - title: Usage
      const: usage
      description: Bandwidth usage

    - title: Clients
      const: clients
      description: Total clients number

    - title: Bitrate
      const: bitrate
      description: Total output bitrate

    - title: Streams
      const: streams
      description: Streams number
    nullable: true
