type: object
properties:
  ssl_protocols:
    type: array
    items:
      allOf:
      - $ref: '../../schemas.yml#/tls_version'
    nullable: true
    description: List of SSL protocol versions that will be used for listening.
    example: [tlsv1.1, tlsv1.2]
  certificate:
    type: string
    description: Path to ssl certificate
    example: /etc/letsencrypt/live/central/fullchain.pem
    x-scope:
      - central
  certificate_key:
    type: string
    description: Path to ssl certificate key
    example: /etc/letsencrypt/live/central/privkey.pem
    x-scope:
      - central


