get:
  operationId: package_get
  summary: Get the package
  description: |
    Package is a group of streams (channels), that are provided together
    to customer as a single billing item.
  parameters:
  - name: name
    description: package name
    in: path
    required: true
    schema:
      example: sports
      type: string
    style: simple
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: '../../components/schemas.yml#/package_config'
      description: Whole package
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: '../../components/schemas.yml#/error_response'
  tags:
  - iptv
put:
  operationId: package_save
  summary: Save the package
  description: |
    Create or update the package.

    Partial configuration can be provided.
  parameters:
  - name: name
    description: package name
    in: path
    required: true
    schema:
      example: sports
      type: string
    style: simple
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../components/schemas.yml#/package_config'
    description: Partial package configuration
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: '../../components/schemas.yml#/package_config'
      description: Updated package
    '400':
      content:
        application/json:
          schema:
            $ref: '../../components/schemas.yml#/error_response'
      description: Couldn't save
  tags:
  - iptv
delete:
  operationId: package_delete
  summary: Delete the package
  description: |
    Delete this package with all links to streams and all links to subscribers.
  parameters:
  - name: name
    description: package name
    in: path
    required: true
    schema:
      example: sports
      type: string
    style: simple
  responses:
    '204':
      description: Deleted
  tags:
  - iptv
