type: object
properties:
  login:
    type: string
    nullable: true
    description: Login
    example: 'secretlogin'
  password:
    type: string
    nullable: true
    description: Password
    example: 'passw'
required:
  - login
  - password
