type: object
properties:
  prefix:
    type: string
    format: media_name
    x-primary-key: true
    description: |
      HTTP prefix that will be intercepted by this lua script
  path:
    type: string
    format: disk_path
    description: |
      Path to the lua handler
  extra:
    x-private: true
    type: object
    additionalProperties:
      type: string
    nullable: true
    description: |
      Some additional options.
required:
- prefix
- path
